apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: booking
    tier: frontend
spec:
  replicas: 3 # how many replicas does it have
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3