apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gpu-demo
spec:
  replicas: 1
  template:
    metadata:
       labels:
         run: gpu-demo
    spec:
      containers:
      - name: gpu-demo
        image: nvidia/cuda-ppc64le:8.0-runtime
        command: ["/bin/sh", "-c"]
        args: ["nvidia-smi && tail -f /dev/null"]
        resources:
          limits:
            nvidia.com/gpu: 1
