apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-qos
  namespace: memory-demo
spec:
  containers:
  - name: memory-demo-qos
    image: polinux/stress
    resources:
      limits:
        memory: "120M"
        cpu: "1"
      requests:
        memory: "120M"
        cpu: "1"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]
