apiVersion: v1
kind: Pod
metadata:
  name: memory-demo-oom
spec:
  containers:
  - name: memory-demo-oom
    image: mycluster.icp:8500/default/stress-ppc64le
    resources:
      limits:
        memory: "200M"
      requests:
        memory: "50M"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
