apiVersion: v1
kind: Service
metadata:
  name: nginx-ppc64le
  namespace: default
spec:
  ports:
  - name: nginx-ppc64le
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-ppc64le
  type: NodePort
